
image: "rust:latest"

stages:
    - test
    - build

test:cargo:
    stage: test
    script:
        - rustc --version && cargo --version  # Print version info for debugging
        - cargo test --workspace --verbose


release:
    only:
        - main
    stage: build
    script: cargo build --release
    artifacts:
        paths:
        - ./build/

build:
    except:
        - main
    stage: build
    script: cargo build
    artifacts:
      
      paths:
        - ./build/
