
image: "rust:latest"

default:
    before_script:
        - echo "[source.crates-io]" >> /usr/local/cargo/config
        - echo "replace-with = 'mirror'" >> /usr/local/cargo/config
        - echo "[source.mirror]" >> /usr/local/cargo/config
        - echo "registry =  \"sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/\"" >> /usr/local/cargo/config

stages:
    - test
    - build


cache:
   key: "$CI_COMMIT_REF_SLUG"
   paths:
       - ~/.cargo/
       - ./target/

test:cargo:
    stage: test
    script:
        - echo $CARGO_HOME
        - rustc --version && cargo --version  # Print version info for debugging
        - cargo test --workspace --verbose


release:
    cache:
        policy: pull
        paths:
            - ~/.cargo
            - ./target
    only:
        - main
    stage: build
    script: 
        - RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup target add x86_64-unknown-linux-musl
        - RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup target add x86_64-pc-windows-gnu
        - cargo build --release --target x86_64-unknown-linux-musl
        - cargo build --release --target x86_64-pc-windows-gnu
    artifacts:
        paths:
        - ./build/

build:
    except:
        - main
    stage: build
    script: 
        - RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup target add x86_64-unknown-linux-musl
        - RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup target add x86_64-pc-windows-gnu
        - cargo build --target x86_64-unknown-linux-musl
        - cargo build --target x86_64-pc-windows-gnu
    artifacts:
      paths:
        - ./build/
